id: P287BB442
initial_creation_type: input
source_metadata:
  title: Ucchuṣma Series
  language: bo
  description: 'Texts related to Ucchuṣma (sme brtsegs), a wrathful deity who is associated
    with the purification of defilements and whose name is sometimes given as Bhurkuṃkūṭa:'
  volume:
    e3434032299f45ef9fe0056ea94cfb19:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    fb82d58f5cf1411bae5edf0da5372e23:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Sādhanas
    a07ded0493664a658a55b5e19882f81c:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    e93bba91e3d04a39b131b7b354d721c7:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Practices
created_at: '2022-03-01T06:28:10.169304'
last_modified_at: '2022-03-01T06:28:10.169306'
